spring.application.name=ingestion-service

# virtual threads
spring.threads.virtual.enabled=true

#postgres with localhost port 5432 defined in docker
spring.datasource.url=jdbc:postgresql://localhost:5432/ingestion_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#kafka connection
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=ingestion-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer